// <auto-generated />
using System;
using Fisrt_App.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fisrt_App.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240509151407_Cards")]
    partial class Cards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fisrt_App.DAL.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ListBoardId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ListBoardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription1",
                            ListBoardId = 1,
                            Title = "MyCard1"
                        },
                        new
                        {
                            Id = 4,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription2",
                            ListBoardId = 1,
                            Title = "MyCard2"
                        },
                        new
                        {
                            Id = 5,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription3",
                            ListBoardId = 1,
                            Title = "MyCard3"
                        },
                        new
                        {
                            Id = 6,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription4",
                            ListBoardId = 1,
                            Title = "MyCard4"
                        },
                        new
                        {
                            Id = 7,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription5",
                            ListBoardId = 1,
                            Title = "MyCard5"
                        },
                        new
                        {
                            Id = 8,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription6",
                            ListBoardId = 2,
                            Title = "MyCard6"
                        },
                        new
                        {
                            Id = 9,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription7",
                            ListBoardId = 2,
                            Title = "MyCard7"
                        },
                        new
                        {
                            Id = 10,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription8",
                            ListBoardId = 2,
                            Title = "MyCard8"
                        },
                        new
                        {
                            Id = 11,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription9",
                            ListBoardId = 2,
                            Title = "MyCard9"
                        },
                        new
                        {
                            Id = 12,
                            Deadline = new DateOnly(1, 1, 1),
                            Description = "MyDescription10",
                            ListBoardId = 2,
                            Title = "MyCard10"
                        });
                });

            modelBuilder.Entity("Fisrt_App.DAL.Entities.ListBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ListBoards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "MyBoard1"
                        },
                        new
                        {
                            Id = 2,
                            Title = "MyBoard2"
                        });
                });

            modelBuilder.Entity("Fisrt_App.DAL.Entities.Card", b =>
                {
                    b.HasOne("Fisrt_App.DAL.Entities.ListBoard", "ListBoard")
                        .WithMany("Cards")
                        .HasForeignKey("ListBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListBoard");
                });

            modelBuilder.Entity("Fisrt_App.DAL.Entities.ListBoard", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
